name: convert to hugo

on:
  push:
    branches:
      - main

jobs:
  convert_to_hugo:
    name: Convert to Hugo
    env:
      EMAIL: ${{ secrets.EMAIL }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
            fetch-depth: 0
            
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: chmod +x ./push_to_hugo.sh && ./push_to_hugo.sh
          
    

        