name: convert to hugo

on:
  push:
    branches:
      - main

jobs:
  convert_to_hugo:
    name: Convert to Hugo
    env:
      EMAIL: ${{ secrets.EMAIL }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: chmod +x ./convert_to_hugo.sh && ./convert_to_hugo.sh

        - name: Publish to Remote
          env: 
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
          uses: dmnemec/copy_file_to_another_repo_action@main
          with:
            source_file: 'notes'
            destination_repo: 'isurunix/isurubuddhika.dev'
            destination_folder: 'content' # optional
            user_email: ${{ secrets.EMAIL }}
            user_name: 'isurunix'           # your login
            commit_message: 'Published from Obsidian Notes'
        
        - name: Clean up
          run: rm -rf ./notes

    
          
          
    

        