name: convert to hugo

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install obsidian-to-hugo 
        - run: python -m obsidian_to_hugo --obsidian-vault-dir=system-design --hugo-content-dir=content

        