name: convert to hugo

on:
  push:
    branches:
      - main

jobs:
  convert_to_hugo:
    name: Convert to Hugo
    env:
      EMAIL: ${{ secrets.EMAIL }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
            fetch-depth: 0
            
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
            
        - run: pip install obsidian-to-hugo 
        - run: python -m obsidian_to_hugo --obsidian-vault-dir=system-design --hugo-content-dir=isurubuddhika.dev/content/notes

        name: Push to Hugo
        - run: |
          git config user.email ${{ secrets.EMAIL }}
          git config user.name "Isuru Buddhika Pathirana"
          cd isurubuddhika.dev
          git commit -a -m "Publishing from Obsidian"
          git push --recurse-submodules=on-demand
    

        