name: Deploy blog from Obsidian

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish Obsidian notes to Github pages
    steps:
      - uses: haxrob/obsidian-to-hugo-pages@main
        with:
          vault-path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}